title: jaiverma.github.io
email: jai2.verma@outlook.com
url: "https://jaiverma.github.io"
baseurl: "/"

twitter_username: _jaiverma
github_username:  jaiverma

header_pages:
    - index.md
    - about.md

footer: 'contact me: <a href="https://twitter.com/_jaiverma">twitter</a>, <a href="mailto:jai2.verma@outlook.com">mail</a>, <a href="https://github.com/jaiverma">github</a>'

# Build settings
markdown: kramdown

# 'theme' is just used for local testing, use 'remote_theme' when pushing to
# GH pages
# theme: blackandpink
remote_theme: jaiverma/blackandpink

highlighter: rouge

plugins:
  - jekyll-feed

collections:
  posts:
    permalink: /blog/:title

disqus:
  shortname: jaiverma-github-io

google_analytics: UA-117692138-1
